---
- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "/usr/local/bin/docker-compose"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: ensure dependencies are installed on debian
  apt:
    pkg: ['python-setuptools',
          'python3-pip']
    state: present
    update_cache: true
    cache_valid_time: 5400
  changed_when: false
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: ensure dependencies are installed on centos/redhat
  yum:
    pkg: [
      'epel-release',
      'python-setuptools'
    ]
    state: present
  changed_when: false
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: ensure pip are installed on centos/redhat
  yum:
    pkg: python-pip
    state: present
  changed_when: false
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install docker compose
  pip:
    name: docker-compose
    executable: /usr/bin/pip3
    state: present
    version: '{{ docker_compose_version | default(omit) }}'
  changed_when: false
  notify:
    - restart docker-compose
  when: ansible_facts['distribution'] == "Ubuntu"

- name: install curl on centos
  yum:
    name: curl
    state: present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

- name: Check if Docker Compose is installed on centos or amazon
  command: docker-compose --version
  register: docker_compose_check
  ignore_errors: yes
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or ansible_facts['distribution'] == "Amazon"

- name: Download and install Docker Compose on centos
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0755
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1
    - (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

- name: Download and install Docker Compose on Amazon linux
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0755
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1
    - ansible_facts['distribution'] == "Amazon"
