---

- name: Ensure docker config folder is present
  changed_when: false
  ansible.builtin.file:
    path: /etc/docker
    mode: 0644
    state: directory

- name: Ensure docker group present
  ansible.builtin.group:
    name: Docker
    state: present
    system: true

- name: Ensure docker user present
  ansible.builtin.user:
    append: true
    groups: docker
    state: present
    name: '{{ item }}'
  with_items: '{{ docker_users or [] }}'
