---

- name: Configure

  ansible.builtin.import_tasks: configure.yml
- name: Docker
  ansible.builtin.import_tasks: docker.yml
- name: Compose
  ansible.builtin.import_tasks: compose.yml
  when: docker_compose_install
