---

# handlers for ansible-role-docker
- name: Restart docker
  ansible.builtin.service:
    name: Docker
    state: restarted
    enabled: true

- name: Start docker
  ansible.builtin.service:
    name: Docker
    state: started
    enabled: true

- name: Reload docker
  ansible.builtin.service:
    name: Docker
    state: reloaded
    enabled: true

- name: Restart docker-compose
  ansible.builtin.service:
    name: Docker-compose
    state: restarted
    enabled: true

- name: Start docker-compose
  ansible.builtin.service:
    name: Docker-compose
    state: started
    enabled: true

- name: Reload docker-compose
  ansible.builtin.service:
    name: Docker-compose
    state: reloaded
    enabled: true
